name: custom deploy

on:
  push:
    branches: [ main ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v3

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 18  # 任意バージョン指定

      - name: Install dependencies
        run: npm ci

      - name: Build
        run: npm run build  # distフォルダなどが生成される

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v1
        with:
          path: './dist'  # ビルド結果のフォルダを指定
        if: ${{ success() }}

      - name: Deploy
        uses: actions/deploy-pages@v1
        if: ${{ success() }}
